"""
Generates a newsletter draft from a MeetingAnalysis object.

Output is a Markdown file ready for paste into Beehiiv (or any newsletter platform).
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Optional

from .analyze_meeting import MeetingAnalysis


DRAFT_TEMPLATE = """\
# {city_name} Council Watch | {date}

> *Draft generated by AI — please review, edit, and add your commentary before publishing.*
> *Editor prompts are marked with 📝 — delete before sending.*

---

## This Week in {city_name}

{meeting_summary}

---

## How They Voted

{votes_section}

---

## What They Said

{quotes_section}

---

## On the Horizon

{on_the_horizon}

---

## Topics Covered This Meeting

{topics_section}

{consistency_section}
---

*{city_name} Council Watch is an independent newsletter tracking local government in {city_name}, {state}.
Written by [Your Name]. Published after each City Council meeting.*

*Have a tip or correction? Reply to this email.*

---

## 📝 Editor's Notes (delete before sending)

{editors_notes}
"""


def _format_votes_section(key_decisions: list[dict]) -> str:
    if not key_decisions:
        return "_No formal votes recorded in this meeting._"

    lines = []
    for decision in key_decisions:
        lines.append(f"**{decision.get('motion', 'Unknown motion')}**")
        result = decision.get("result", "Unknown")
        breakdown = decision.get("vote_breakdown", "")
        lines.append(f"*Result: {result}{' (' + breakdown + ')' if breakdown else ''}*")

        votes = decision.get("votes", {})
        if votes:
            vote_lines = []
            for member, vote in votes.items():
                emoji = {"Yes": "✅", "No": "❌", "Abstain": "⚪", "Absent": "—"}.get(vote, "•")
                vote_lines.append(f"  - {emoji} **{member}**: {vote}")
            lines.extend(vote_lines)

        significance = decision.get("significance", "")
        if significance:
            lines.append(f"\n*{significance}*")

        lines.append("")

    return "\n".join(lines)


def _format_quotes_section(notable_quotes: list[dict]) -> str:
    if not notable_quotes:
        return "_No notable quotes captured._"

    lines = []
    for q in notable_quotes:
        speaker = q.get("speaker", "Unidentified")
        quote = q.get("quote", "")
        context = q.get("context", "")
        lines.append(f"> \"{quote}\"\n> — *{speaker}*")
        if context:
            lines.append(f"\n{context}")
        lines.append("")

    return "\n".join(lines)


def _format_topics_section(topics: list[str]) -> str:
    if not topics:
        return "_Topics not extracted._"
    return ", ".join(f"**{t}**" for t in topics)


def _format_consistency_section(flags: list[dict]) -> str:
    if not flags:
        return ""

    lines = ["\n---\n\n## Worth Watching\n"]
    for flag in flags:
        member = flag.get("council_member", "A council member")
        obs = flag.get("observation", "")
        lines.append(f"- **{member}**: {obs}")
    lines.append("")
    return "\n".join(lines)


def _format_editors_notes(prompts: list[str]) -> str:
    if not prompts:
        return "_No editor prompts generated._"
    return "\n".join(f"- 📝 {p}" for p in prompts)


def generate_draft(
    analysis: MeetingAnalysis,
    city_config: dict,
    meeting_date: Optional[datetime] = None,
    output_dir: Optional[Path] = None,
) -> str:
    """
    Generate a newsletter draft from a MeetingAnalysis.

    Returns the draft as a string and optionally saves it to output_dir.
    """
    date_str = (meeting_date or datetime.now()).strftime("%B %d, %Y")
    city_name = city_config["name"]
    state = city_config["state"]

    draft = DRAFT_TEMPLATE.format(
        city_name=city_name,
        state=state,
        date=date_str,
        meeting_summary=analysis.meeting_summary or "_Summary not available._",
        votes_section=_format_votes_section(analysis.key_decisions),
        quotes_section=_format_quotes_section(analysis.notable_quotes),
        on_the_horizon=analysis.on_the_horizon or "_No upcoming items captured._",
        topics_section=_format_topics_section(analysis.topics_discussed),
        consistency_section=_format_consistency_section(analysis.consistency_flags),
        editors_notes=_format_editors_notes(analysis.editors_note_prompts),
    )

    if output_dir is not None:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{city_name.lower().replace(' ', '-')}_{(meeting_date or datetime.now()).strftime('%Y-%m-%d')}.md"
        output_path = output_dir / filename
        output_path.write_text(draft)
        print(f"Draft saved to: {output_path}")

    return draft
